application: kbp264
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: static/css

- url: /new_images
  static_dir: static/new_images

- url: /images
  static_dir: static/images

- url: /scripts
  static_dir: static/scripts

- url: /jqzoom_js
  static_dir: static/jqzoom_ev-2.3/js

- url: /jqzoom_css
  static_dir: static/jqzoom_ev-2.3/css

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.2"
